### PR TITLE
Fix vagrant dependency in Gemfile

### PR DESCRIPTION
**Pull request by dobbymoodge**
Addresses issue #430. Satisfy dependency from installed gem if
possible.

### CODE REVIEW

**Comment by dobbymoodge** [comment]
@danmcp

**Comment by danmcp** [comment]
@dobbymoodge Find this from somewhere of did you figure it out?

Also need to fix the readme about the previous error.

**Comment by dobbymoodge** [comment]
@danmcp I copied it from here:
https://github.com/mitchellh/vagrant/blob/master/Gemfile

I'm not 100% clear on how it works exactly, but it does seem to work.

I'll update the readme later this morning and remove the [WIP]

**Comment by dobbymoodge** [comment]
@danmcp Updated docs

**Comment by stevekuznetsov** [comment]
@dobbymoodge doesn't seem to wok for me:
```
$ bundle && bundle exec rake
Updating git://github.com/mitchellh/vagrant.git
Fetching gem metadata from https://rubygems.org/.........
Fetching additional metadata from https://rubygems.org/..
Resolving dependencies...
Using rake 11.1.2
Using CFPropertyList 2.3.2
Using builder 3.2.2
Using bundler 1.7.8
Using ffi 1.9.10
Using childprocess 0.5.9
Using coderay 1.1.1
Using unf_ext 0.0.7.2
Using unf 0.1.4
Using domain_name 0.5.20160310
Using erubis 2.7.0
Using excon 0.49.0
Using fission 0.5.0
Using formatador 0.2.5
Using fog-core 1.40.0
Using multi_json 1.12.1
Using fog-json 1.0.2
Using ipaddress 0.8.3
Using xml-simple 1.1.5
Using fog-aliyun 0.1.0
Using mini_portile2 2.0.0
Installing nokogiri 1.6.7.1
Installing fog-xml 0.1.2
Installing fog-atmos 0.1.0
Installing fog-aws 0.9.2
Installing inflecto 0.0.2
Installing fog-brightbox 0.10.1
Installing fog-cloudatcost 0.1.2
Installing fog-dynect 0.0.3
Installing fog-ecloud 0.3.0
Installing fog-google 0.1.0
Installing fog-local 0.3.0
Installing fog-openstack 0.1.6
Installing fog-powerdns 0.1.1
Installing fog-profitbricks 0.0.5
Installing fog-rackspace 0.1.1
Installing fog-radosgw 0.0.5
Installing fog-riakcs 0.1.0
Installing fog-sakuracloud 1.7.5
Installing fog-serverlove 0.1.2
Installing fog-softlayer 1.1.1
Installing fog-storm_on_demand 0.1.1
Installing fog-terremark 0.1.0
Installing fog-vmfusion 0.1.0
Installing fog-voxel 0.1.0
Installing trollop 2.1.2
Installing rbvmomi 1.8.2
Installing fog-vsphere 0.7.0
Installing fog-xenserver 0.2.3
Installing fog 1.38.0
Installing gssapi 1.2.0
Installing gyoku 1.3.1
Using hashicorp-checkpoint 0.1.4
Using http-cookie 1.0.2
Installing httpclient 2.8.0
Using i18n 0.7.0
Using json 1.8.3
Installing rb-fsevent 0.9.7
Installing rb-inotify 0.9.7
Installing listen 3.0.8
Installing little-plugger 1.1.4
Using log4r 1.1.10
Installing logging 2.1.0
Installing method_source 0.8.2
Installing mime-types 2.99.2
Installing net-ssh 3.0.2
Installing net-scp 1.1.2
Using net-sftp 2.1.2
Installing netrc 0.11.0
Installing nori 2.6.0
Installing slop 3.6.0
Installing pry 0.10.3
Installing rb-kqueue 0.2.4
Using rest-client 1.8.0
Installing rubyntlm 0.6.0
Installing rubyzip 1.2.0
Using thor 0.19.1
Installing wdm 0.1.1
Installing winrm 1.8.1
Installing winrm-fs 0.3.2
Using vagrant 1.8.2.dev from git://github.com/mitchellh/vagrant.git (at master)
Installing vagrant-aws 0.7.0
Using vagrant-openshift 3.0.8 from source at .
Your bundle is complete!
Use `bundle show [gemname]` to see where a bundled gem is installed.
vagrant-openshift 3.0.8 built to pkg/vagrant-openshift-3.0.8.gem.
git://github.com/mitchellh/vagrant.git (at master) is not yet checked out. Run `bundle install` first.
```

**Pull request merged**
