### PR TITLE
don't rebuild images that don't have a new commit

### PR DESCRIPTION
**Pull request by bparees**

### CODE REVIEW

**Comment by bparees** [comment]
@mfojtik ptal.  this is intended mostly to avoid rebuilding the base image if the commit hasn't actually changed.  currently we spend a huge amount of time rebuilding the base image on every push job, even though it's usually not the image that changed.

also prepulling the base images is pointless now since they are squashed so we don't get any benefit during the rebuild of the base image, from having pulled it already.

**Comment by bparees** [comment]
(note that we'll still end up pushing the image back up to the registry even if we didn't build it, but that should be pretty fast)

**Comment by mfojtik** [comment]
what happens if the internal registry is pruned?

**Comment by bparees** [comment]
the pull will fail and we'll rebuild?

**Comment by bparees** [comment]
@mfojtik any other comments on this?

**Comment by mfojtik** [comment]
LGTM

**Pull request merged**
