### PR TITLE
add lsof, strace, tcpdump to base deps

### PR DESCRIPTION
**Pull request by jim-minter**

### CODE REVIEW

**Comment by jim-minter** [comment]
@danmcp ptal

**Comment by danmcp** [comment]
[test]

**Comment by danmcp** [comment]
@dobbymoodge @stevekuznetsov What's going on with this: https://github.com/openshift/vagrant-openshift/pull/482/files ?

**Comment by dobbymoodge** [comment]
Blocked on Steve, AFAIK. I still haven't found a good fix for the
bundler/vagrant weirdness.

**Comment by stevekuznetsov** [comment]
I think it can merge as it is.

**Comment by danmcp** [comment]
@stevekuznetsov So you have given up on fixing bundle exec rake?

**Comment by stevekuznetsov** [comment]
> fixing

It's functional either way as it's written today. When I have more bandwidth, I can look into it but as of today the only downside to implementing it that way is people lucky enough to not have the bug have to install the plugin twice. It's a cost of some fraction of a second that a user won't be likely to notice.

**Comment by dobbymoodge** [comment]
I think it's worth me taking a third look at in the future, but it's not worth blocking anything now.

**Pull request merged**
