### PR TITLE
add rhaos36 repo

### PR DESCRIPTION
**Pull request by gabemontero**
@stevekuznetsov @smunilla @bparees  .... I'm assuming it is not too soon to do this

of course if it is, or if more is involved to access 3.6 ose rpms from our vagrant sessions, plmk

thanks

### CODE REVIEW

**Comment by bparees** [comment]
lgtm but will let @smunilla confirm we're at a point where we can use the new repo.

**Comment by stevekuznetsov** [comment]
You'll also need to update the `origin-ci-tool` [here](https://github.com/openshift/origin-ci-tool/blob/master/oct/ansible/oct/roles/dependencies/tasks/register_repositories.yml#L28-L33)

**Comment by gabemontero** [comment]
https://github.com/openshift/origin-ci-tool/pull/114 submitted

**Comment by stevekuznetsov** [comment]
@smunilla @jupierce ping

**Comment by stevekuznetsov** [comment]
@smunilla @jupierce ping

**Comment by bparees** [comment]
honestly this is probably going to be moot really soon.  between @smunilla's new job for building rhel jenkins images the right way, and my reworking the existing jenkins rhel image builder job to use oct, the vagrant code won't matter anymore soon enough, i believe.

**Comment by stevekuznetsov** [comment]
@bparees also asking for the linked `oct` PR that Gabe made

**Comment by smunilla** [comment]
👍

**Comment by gabemontero** [comment]
short term, it might benefit me wrt getting 3.6 jenkins images built to have this merged and have https://ci.openshift.redhat.com/jenkins/view/All/job/vagrant-openshift/ run to bring in the update.  AWS AMI's I provision via `oct` are giving me issues wrt having to run the yum cfg-mgr to enable rhaos repos that I haven't been able to sort out by hand when I run `make test TARGET=rhel7` from a clone of https://github.com/openshift/jenkins.git

Certainly long term I'm good with sorting through those type of issues and leveraging `oct`, but given the time crunch wrt 3.6 jenkins images, having vagrant with a rhaos36.repo file looks to be most expedient.

**Comment by bparees** [comment]
just add the repo to your own ec2 instance (and the rhel7 image on that instance) if you want to test building the image yourself.

**Comment by stevekuznetsov** [comment]
@gabemontero can you do the roll-out after merge?

**Comment by gabemontero** [comment]
@stevekuznetsov started https://ci.openshift.redhat.com/jenkins/view/All/job/vagrant-openshift/459/console

@bparees I assume putting the repo in my ec2 instance means creating a rhaos36.repo in /etc/yum.repos.d on my instance.   Apologies, but can you elaborate on what you mean by "and the rhel7 image on that instance?

**Comment by bparees** [comment]
you need to simulate what the install_origin_rhel7.rb does:

1) you need to create all the repo files in /etc/yum.repos.d  (in this case just your new rhaos36 one)
2) you copy all that content to a working dir:

```
# inside temporary directory create docker build context for the new base image
contextdir=$(mktemp -d)

# copy the necessary files
mkdir $contextdir/{certs,repos,vars,keys}
cp /var/lib/yum/*.pem $contextdir/certs
cp /etc/yum/vars/* $contextdir/vars
cp /etc/yum.repos.d/* $contextdir/repos
cp /etc/pki/rpm-gpg/* $contextdir/keys

# Remove repositories we won't be needing and which require RH certs
rm -rf $contextdir/repos/redhat-rhui*

# remove google chrome repo
rm -rf $contextdir/repos/*chrome*.repo

# remove local openshift epel mirror - we will only temporarily mount this via imagebuilder during image builds
rm -rf $contextdir/repos/local_epel.repo 
```

3) you write a dockerfile that will ADD all the repo content to a rhel7.2 image (we'll move to 7.3 soon, but for now our Dockerfile.rhel7 references rhel7.2 i believe):

```
FROM registry.access.redhat.com/rhel7.2:latest

RUN yum remove -y subscription-manager

ADD vars/* /etc/yum/vars/
ADD repos/* /etc/yum.repos.d/
ADD certs/* /var/lib/yum/
ADD keys/* /etc/pki/rpm-gpg/

RUN yum update -y && yum clean all
```

4) you docker build it:
docker build --rm -t rhel7.2 $contextdir

now you've got a local "rhel7.2" image which contains all the right repos, and you can build the jenkins rhel image on top of it (the jenkins rhel7 dockerfile should say "FROM rhel7.2"

**Comment by gabemontero** [comment]
Ah - thanks for the details @bparees 

@stevekuznetsov - the vagrant publish failed with 

```
Bundler could not find compatible versions for gem "ruby":
  In Gemfile:
    ruby

    vagrant was resolved to 1.9.7.dev, which depends on
      ruby (< 2.4, ~> 2.2)
Build step 'Execute shell' marked build as failure
```

If there is a quick fix, great, but otherwise/in the interim I'll move forward with the steps @bparees outlined above (understanding that vagrant-openshift is low priority at this point).

**Comment by bparees** [comment]
getting a new ami built is going to take hours, assuming we're even able to build amis currently.  i wouldn't wait for it.

**Comment by dobbymoodge** [comment]
Not sure RHSCL is the solution here. I'm pretty sure we just need to specify version 1.7.4 for the vagrant gem. Looking into it now.

**Comment by dobbymoodge** [comment]
Fixed by running `bundler` like:
```
bundle _1.5.3_ install --path ./bundle
```

**Comment by stevekuznetsov** [comment]
@dobbymoodge @gabemontero OK, confirm we got the new Vagrant updated correctly?

**Pull request merged**
