### PR TITLE
Add go vet to dependencies

### PR DESCRIPTION
**Pull request by stevekuznetsov**
In order to allow https://github.com/openshift/origin/pull/4118

@derekwaynecarr  PTAL

### CODE REVIEW

**Comment by bparees** [comment]
@stevekuznetsov did you confirm w/ someone that this is the right way to do this, vs calling hack/install-tools.sh?

**Comment by stevekuznetsov** [comment]
@bparees Was expecting @derekwaynecarr  to weigh in on that.

**Comment by derekwaynecarr** [comment]
I am not familiar with hack/install-tools.sh, but as for installing go vet this LGTM to me.

**Comment by derekwaynecarr** [comment]
@stevekuznetsov I assume you tested the change to the plug-in and verified that it installed the expected dependency?

**Comment by liggitt** [comment]
I don't think the openshift source has been cloned to the machine at this point. I'm ok merging this

**Pull request merged**
