### PR TITLE
Fixed the way we pass focus flag to extended tests

### PR DESCRIPTION
**Pull request by soltysh**
Based on [this email](http://lists.openshift.redhat.com/openshift-archives/dev/2015-October/msg00035.html) I've modified the flag we're passing. @danmcp

### CODE REVIEW

**Comment by mfojtik** [comment]
LGTM @smarterclayton double check

**Comment by bparees** [comment]
@deads2k can probably confirm for us.

**Comment by deads2k** [comment]
> @deads2k can probably confirm for us.

I haven't tried the new flag format.

**Comment by bparees** [comment]
@php-coder i think you were playing with focus flags recently, can you confirm this is the correct new syntax?

**Comment by php-coder** [comment]
@bparees As far I remember it was @PI-Victor (I havn't play with extended tests yet.)

**Comment by PI-Victor** [comment]
yes i use ./core --ginkgo.focus={"description one","description two", "..."} for multiple tests and --ginkgo.focus="description one" to run a single extended tests

**Comment by bparees** [comment]
@PI-Victor great, thanks.

**Pull request merged**
