### PR TITLE
added more steps to local dev for README

### PR DESCRIPTION
**Pull request by stevekuznetsov**
The current steps are incomplete and incorrect, and this attempts to fix that. Until the error from `bundle exec rake` can be fixed, it is also useful to mention in the README that it is OK to see the error and continue.

@danmcp @bparees

### CODE REVIEW

**Comment by bparees** [comment]
lgtm

**Comment by stevekuznetsov** [comment]
@bparees do you want to update the plugin / kick jobs or should I? :)

**Comment by bparees** [comment]
@stevekuznetsov all you changed is the readme, there's no reason to update the plugin on jenkins...

**Comment by danmcp** [comment]
@bparees @stevekuznetsov Quitters

**Comment by stevekuznetsov** [comment]
@bparees therein lies the joke

@danmcp guilty as charged

**Pull request merged**
