### PR TITLE
Running the end-to-end tests with sudo prevents chromedriver from lau…

### PR DESCRIPTION
**Pull request by brenton**
…nching

I ran the 'make test' command manually and as part of the test-openshift plugin
and neither required root.

### CODE REVIEW

**Comment by brenton** [comment]
@jwforres, @ncdc Does this sounds OK to you?

I'm curious if anyone knows if the extended test actually need sudo or not.

**Comment by ncdc** [comment]
When I run tests, I never use sudo. I can't say I ever do `make test`. I usually just run individual tests directly (`hack/test-end-to-end.sh`, etc.).

However, I don't think I've run e2e since the chrome switch. I'll have to defer to others on this one.

**Comment by jwforres** [comment]
@deads2k has been looking at the tests a lot recently... do you know the
answer?

On Mon, Sep 14, 2015 at 3:39 PM, Brenton Leanhardt <notifications@github.com

**Comment by deads2k** [comment]
> I'm curious if anyone knows if the extended test actually need sudo or not.

Extended tests and e2e tests both require `sudo` to bind our DNS port, to write iptables rules, and to mount volumes.

**Comment by jwforres** [comment]
But the test itself is calling the commands with sudo right, the question
is do you need to run `sudo hack/test-end-to-end.sh`

**Comment by ncdc** [comment]
The code in hack/util.sh uses sudo to start openshift, so (at least in the recent past) it isn't necessary to use sudo to invoke hack/test-end-to-end.sh.

**Comment by deads2k** [comment]
> But the test itself is calling the commands with sudo right, the question
> is do you need to run `sudo hack/test-end-to-end.sh`

Oh, you shouldn't have to.  That would be an unintentional side-effect of something.

**Comment by brenton** [comment]
For what it's worth I just kicked off a run of the extended tests to see if sudo is needed there.

**Comment by brenton** [comment]
The extended tests reported a lot of failures though I don't know if they are related to sudo.  They actually aren't working right now in jenkins for other unrelated reasons:   https://ci.openshift.redhat.com/jenkins/job/origin_extended/58/consoleText.  My vote would be to merge this change in so we could at least get the rhel7 devenv_ami working.  We can debug the extended tests failures separately.  @danmcp, would you be ok with that?

**Comment by danmcp** [comment]
> @danmcp, would you be ok with that?
@brenton +1

**Pull request merged**
