### PR TITLE
add empty string arg to test-go

### PR DESCRIPTION
**Pull request by bparees**

### CODE REVIEW

**Comment by stevekuznetsov** [comment]
@bparees could you please clarify whether `hack/test-go` needed this nonsense or `test go` needed it?

**Comment by bparees** [comment]
@stevekuznetsov not certain but i suspect it was hack/test-go that i was referring to.

**Comment by bparees** [comment]
I think hack/test-go expected an additional arg.

**Comment by stevekuznetsov** [comment]
Ok. New impl of `hack/test-go` can handle this for now, will fix soon.

**Pull request merged**
