### PR TITLE
Added --extended option for test-openshift3

### PR DESCRIPTION
**Pull request by mfojtik**

### CODE REVIEW

**Comment by mfojtik** [comment]
@bparees @danmcp this depends on https://github.com/openshift/origin/pull/1395

**Comment by danmcp** [comment]
It's a little confusing that all doesn't include extended.

**Comment by bparees** [comment]
agree... are we using --all anywhere today that would be impacted by having --all start running extended?

**Comment by mfojtik** [comment]
@bparees @danmcp is --all what we do run by default? i thought the extended should be 'optional'

**Comment by danmcp** [comment]
We run --all from test/merge/ami.

Seems like the right thing to do is rename --all to be something else.  And change the jenkins jobs.

**Comment by mfojtik** [comment]
@danmcp how about having --all and --exclude-extended ? ;-)

**Comment by danmcp** [comment]
@mfojtik I would rather make them all additions.  Let's just remove --all and make that the default.  And change the jobs to not use it.

**Comment by mfojtik** [comment]
@danmcp ok, will do

**Comment by mfojtik** [comment]
@danmcp I hope I understand your intentions, but now I run **all** tests by default (including the extended). You have options to disable certain tests if you want:

`--no_integration` (run unit tests instead of integration+unit)
`--no_assets` (skip asset testing)
`--no_extended` (skip extended which will be default)

**Comment by bparees** [comment]
This is going to be a confusing interface when someone wants to run specific tests...

I would have voted for all being default, but then have flags to run specific groups and if you specify a group, you only get that group(s)

runtests   - runs all
runtests --integration   - only runs integration
runtests --integration --extended  - runs integration+extended.

**Comment by danmcp** [comment]
@bparees @mfojtik Agree with been about the default.  And I agree the other stuff should be additions.  It would be easiest to make the extended tests a comma separated list to match what v2 and the bot does.

**Comment by mfojtik** [comment]
@bparees @danmcp sorry for the delay, I finally get into fixing this. So I reworked this that by default all tests will run (including extended). You can then use options @bparees describe to run only certain group. I'm going to test this now.

**Comment by bparees** [comment]
ok so we'll need to modify the existing jobs to specify the buckets to run (not extended).

full disclosure:  that's the design i wanted, but i think dan actually wanted the "default" behavior to run what it runs today (everything except extended) so the jobs wouldn't have to change.  i'm still not a fan of that though, seems arbitrary/surprising.

**Comment by mfojtik** [comment]
@bparees I don't think that changing Jenkins jobs is a big pain, you just list all groups, which makes it nicer and clean in a way that you see what is running.

**Comment by bparees** [comment]
@mfojtik no argument here.  just wanted to make sure all POV were represented.

**Comment by danmcp** [comment]
@mfojtik @bparees I don't think we are on the same page yet.  I was looking for all to run everything but extended.  And have a --extended option that takes a list of additional tests to run.

**Pull request closed without merging**
