### PR TITLE
Skip squashing test candidate image to speed up push_images

### PR DESCRIPTION
**Pull request by mfojtik**
@bparees do we want to squash the 'candidate' images? (what is the chance that squashing will alter the tested images in a way that the output (squashed image) will behave differently?

The squashing is taking a significant portion of time during the testing (and you also can't re-use the existing layers when you do make build)

### CODE REVIEW

**Comment by mfojtik** [comment]
@jhadvig PTAL

**Comment by jhadvig** [comment]
@mfojtik it does make sense to skip the squashing, since we dont need less layers but faster tests.  LGTM :+1:

**Comment by jhadvig** [comment]
@mfojtik would it make sense to put this change also into `test_openshift_images.rb` ?

**Comment by bparees** [comment]
The reason I put it in is because we've previously broken the squashing logic and since we only run "make test" in the PR tester job, not running the squash logic during "make test" means that we won't find out we broke the squash logic until the push image job runs.

how much time is it adding?

**Comment by bparees** [comment]
(So not squashing candidate images in the push images job would be ok, as long as we continue to squash candidate images in the test flow)

**Pull request closed without merging**
