### PR TITLE
Make the repo name to URL logic simpler and more generic

### PR DESCRIPTION
**Pull request by stevekuznetsov**
Make the repo name to URL logic simpler and more generic

It is the case for all of the repositories that we currently support in
this project that the 'repository_name' parameter is literally the name
of the project underneath the OpenShift organization on GitHub, so it is
not necessary to have all of the complicated logic around the repository
name to repository URL mapping that we have today. These changes
simplify that logic and thereby also make it more generic, allowing new
repositories to be supported implicitly for commands like
`checkout-repos` and `origin-local-checkout`.

This is a backwards-incompatible change in that the definition of the
`origin` repository no longer contains source-to-image or the Origin web
console, but it does not seem to actually be necessary to clone these
three repositories in tandem. When a Jenkins job in fact needs more than
one repository cloned or updated, it can call out to do this with the
pre-existing `--repo` flag.

Signed-off-by: Steve Kuznetsov <skuznets@redhat.com>

---

Removed dead code

These two modules were entirely unused.

Signed-off-by: Steve Kuznetsov <skuznets@redhat.com>

---

Reformatted changed code for style compliance

Signed-off-by: Steve Kuznetsov <skuznets@redhat.com>

---

/cc @dobbymoodge @bparees this cleans up the code a little so we can get support for the OpenShift Jenkins repository without making the mess bigger. PTAL.

### CODE REVIEW

**Comment by stevekuznetsov** [comment]
Last two commits broken out for review, can squash before merge.

**Comment by bparees** [comment]
lgtm

**Comment by stevekuznetsov** [comment]
@jwforres can you think of any jobs you guys run for the console where you also need to be checking out latest Origin code?

**Comment by jwforres** [comment]
no today we don't check out origin code for our test, we are using the built master that's already on the AMI. Although given the flakiness of the devenv_ami job that means there have been periods of time where the console was not being validated against the latest master.

**Comment by stevekuznetsov** [comment]
Understood -- this won't regress anything, then.

**Comment by dobbymoodge** [comment]
LGTM +1

**Comment by stevekuznetsov** [comment]
[test]

**Comment by stevekuznetsov** [comment]
re[test]... `vagrant clone-upstream-repositories` was doing really silly things

**Comment by stevekuznetsov** [comment]
Issues are just with the test script now, as it is one of the few that actually needs to be dealing with more than one repository at once.

**Comment by stevekuznetsov** [comment]
OK, just unrelated errors during build now. Merging.

**Pull request merged**
