### PR TITLE
Revert "Merge PR's branch with master before testing"

### PR DESCRIPTION
**Pull request by bparees**
This reverts commit ad869880cb7860b98e1cb642fb7563c2ba20e9f1.

### CODE REVIEW

**Comment by bparees** [comment]
@rhcarvalho fyi.  feel free to un-revert after you sort out the issue.

**Comment by smarterclayton** [comment]
Is this the cause of 

```
+ vagrant test-origin --all -d --skip-image-cleanup
/var/lib/jenkins/.vagrant.d/gems/gems/vagrant-openshift-3.0.3/lib/vagrant-openshift/action/download_artifacts_origin.rb:24:in `initialize': wrong number of arguments (2 for 3) (ArgumentError)
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/warden.rb:90:in `new'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/warden.rb:90:in `finalize_action'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/warden.rb:20:in `block in initialize'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/warden.rb:20:in `map'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/warden.rb:20:in `initialize'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/builder.rb:170:in `new'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/builder.rb:170:in `to_app'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/builder.rb:116:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/runner.rb:66:in `block in run'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/util/busy.rb:19:in `busy'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/runner.rb:66:in `run'
	from /var/lib/jenkins/.vagrant.d/gems/gems/vagrant-openshift-3.0.3/lib/vagrant-openshift/command/test_origin.rb:94:in `block in execute'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/plugin/v2/command.rb:226:in `block in with_target_vms'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/plugin/v2/command.rb:220:in `each'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/plugin/v2/command.rb:220:in `with_target_vms'
	from /var/lib/jenkins/.vagrant.d/gems/gems/vagrant-openshift-3.0.3/lib/vagrant-openshift/command/test_origin.rb:92:in `execute'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/cli.rb:42:in `execute'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/environment.rb:301:in `cli'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/bin/vagrant:174:in `<main>'
Build step 'Execute shell' marked build as failure
``` 

from the merge job?

**Comment by bparees** [comment]
@smarterclayton no.  is that happening consistently?

**Comment by smarterclayton** [comment]
Yes, every merge job since about 6pm has failed, and test pull requests is failing as well.

**Comment by bparees** [comment]
https://github.com/openshift/vagrant-openshift/commit/97a00ef59c8b064522ab54c133b663ae77e8fb78#diff-0c417f404cde01770d47a7f242643f01

**Comment by bparees** [comment]
I think that commit broke it, but no one ran the vagrant update job until I did around 6 or 7.

**Pull request merged**
