### PR TITLE
Allow to sync repo with detached head

### PR DESCRIPTION
**Pull request by miminar**
Signed-off-by: Michal Minář <miminar@redhat.com>

### CODE REVIEW

**Comment by miminar** [comment]
[test]

**Comment by danmcp** [comment]
@miminar It's not clear what gets you into this condition and whether we should support it.

**Comment by miminar** [comment]
> @miminar It's not clear what gets you into this condition and whether we should support it.

@danmcp I wanted to checkout older revision of [openshift/source-to-image](https://github.com/openshift/source-to-image/tree/89b96680e451c0fa438446043f967b5660942974) for fork ami job. Unfortunately, there are no branches to choose from except for master. So I tried to set  `S2I_BRANCH` to `89b96680e451c0fa438446043f967b5660942974`.

This makes sync checkout master branch because `git status` invoked from the modified line returns:

```
HEAD detached at 89b9668
nothing to commit, working tree clean
```

which is not matched by original regexp.

**Comment by danmcp** [comment]
@miminar I am debating whether we want to support this or force you to use a branch.

**Comment by miminar** [comment]
> @miminar I am debating whether we want to support this or force you to use a branch.

Since a work-around is available (fork a repo and make a branch), I'm fine with forcing to use a branch. Closing.

**Pull request closed without merging**
