### PR TITLE
enable submodule usage

### PR DESCRIPTION
**Pull request by sosiouxme**

### CODE REVIEW

**Comment by sosiouxme** [comment]
@richm apparently https://github.com/openshift/origin-aggregated-logging/pull/133 is the first time anyone has introduced submodules into something that's tested. I'm honestly not sure how to test that this works and fixes the issue. Thoughts?

**Comment by sosiouxme** [comment]
it might be a little weird if [test] works here...

**Comment by sosiouxme** [comment]
@danmcp I've managed some testing to gain a modicum of confidence that this fix addresses the problem... what should I do to get this merged?

**Comment by danmcp** [comment]
@sosiouxme It's installed now.

**Comment by sosiouxme** [comment]
thx

**Comment by sosiouxme** [comment]
@danmcp it works fine in jenkins AMIs but could it also be released for use with "vagrant plugin install vagrant-openshift" so we can use it for manual tests?

**Comment by danmcp** [comment]
@sosiouxme done

**Pull request merged**
