### PR TITLE
Added extended tests to run_openshift_tests

### PR DESCRIPTION
**Pull request by mfojtik**

### CODE REVIEW

**Comment by mfojtik** [comment]
@bparees I tested this manually against AWS and the tests worked. There seems to be some random failure with waiting for OpenShift server to start. I'm going to increase the timeout for now. It seems rare to happen (I suspect I won some crappy AWS machine).

**Comment by mfojtik** [comment]
And of course this PR is pending having the https://github.com/openshift/origin/pull/3732 merged.

**Comment by mfojtik** [comment]
@jhadvig FYI

**Comment by bparees** [comment]
is :all the default for the test tag?

**Pull request closed without merging**
