### PR TITLE
removed hard-coded directories

### PR DESCRIPTION
**Pull request by stevekuznetsov**
@bparees PTAL

@deads2k FYI

fixes https://github.com/openshift/vagrant-openshift/issues/379

### CODE REVIEW

**Comment by deads2k** [comment]
lgtm.  I don't have merge rights here though.

**Comment by bparees** [comment]
you already updated something else to pick those dirs up, right?

**Comment by bparees** [comment]
(Questions I should ask before merging for $100, alex)

**Comment by deads2k** [comment]
> you already updated something else to pick those dirs up, right?

Our scripts set them up relative to the test directory under $TMPDIR

**Comment by bparees** [comment]
hm.  should this one also have been update:
`cmd_env << 'OUTPUT_COVERAGE=/tmp/origin/e2e/artifacts/coverage'`


?

**Comment by deads2k** [comment]
> hm. should this one also have been updated:
> cmd_env << 'OUTPUT_COVERAGE=/tmp/origin/e2e/artifacts/coverage'

We don't set that one and I don't know what it's for.

**Comment by stevekuznetsov** [comment]
That's one of the obtusely named `hack/test-go.sh` parameters, and no I have not yet updated it in Origin. We could have rolled it in with this but I'll focus on it when my pull for that script goes in.

**Pull request merged**
