### PR TITLE
Use deferred deletion and removal for Docker daemon

### PR DESCRIPTION
**Pull request by stevekuznetsov**
To combat:
 - https://bugzilla.redhat.com/show_bug.cgi?id=1344013
 - https://github.com/openshift/origin/issues/9201

Signed-off-by: Steve Kuznetsov <skuznets@redhat.com>

### CODE REVIEW

**Comment by stevekuznetsov** [comment]
@danmcp builds fine:
```
[Wed Jun  8 15:41:00 EDT 2016] [parent] Starting build of plugin: skuznets/devicemapper...
[Wed Jun  8 15:41:15 EDT 2016] [skuznets-ami-docker-patch] vagrant origin-local-checkout
[Wed Jun  8 15:41:45 EDT 2016] [skuznets-ami-docker-patch] vagrant origin-init
[Wed Jun  8 15:41:46 EDT 2016] [skuznets-ami-docker-patch] vagrant up
[Wed Jun  8 15:43:38 EDT 2016] [skuznets-ami-docker-patch] vagrant build-origin-base
[Wed Jun  8 15:53:30 EDT 2016] [skuznets-ami-docker-patch] vagrant clone-upstream-repos --clean
[Wed Jun  8 15:54:32 EDT 2016] [skuznets-ami-docker-patch] vagrant checkout-repos
[Wed Jun  8 15:54:38 EDT 2016] [skuznets-ami-docker-patch] vagrant build-origin-base-images
[Wed Jun  8 15:59:59 EDT 2016] [skuznets-ami-docker-patch] vagrant build-origin --images
[Wed Jun  8 16:16:04 EDT 2016] [skuznets-ami-docker-patch] vagrant build-sti --binary-only
[Wed Jun  8 16:16:15 EDT 2016] [skuznets-ami-docker-patch] finished
```

**Comment by danmcp** [comment]
@stevekuznetsov And tests after?

**Comment by stevekuznetsov** [comment]
Can we run the `base_ami` job as a test for this repo or something? I can kick another instance with tests... which ones do you want to see? The full suite?

**Comment by danmcp** [comment]
vagrant test-origin --all

**Comment by stevekuznetsov** [comment]
Seemingly unrelated failure...

```
[Thu Jun  9 07:59:17 EDT 2016] [parent] Starting build of plugin: skuznets/devicemapper...
[Thu Jun  9 07:59:31 EDT 2016] [skuznets-ami-docker-patch] vagrant origin-local-checkout
[Thu Jun  9 07:59:59 EDT 2016] [skuznets-ami-docker-patch] vagrant origin-init
[Thu Jun  9 08:00:01 EDT 2016] [skuznets-ami-docker-patch] vagrant up
[Thu Jun  9 08:01:48 EDT 2016] [skuznets-ami-docker-patch] vagrant build-origin-base
[Thu Jun  9 08:10:15 EDT 2016] [skuznets-ami-docker-patch] vagrant clone-upstream-repos --clean
[Thu Jun  9 08:11:42 EDT 2016] [skuznets-ami-docker-patch] vagrant checkout-repos
[Thu Jun  9 08:11:47 EDT 2016] [skuznets-ami-docker-patch] vagrant build-origin-base-images
[Thu Jun  9 08:17:21 EDT 2016] [skuznets-ami-docker-patch] vagrant build-origin --images
[Thu Jun  9 08:33:28 EDT 2016] [skuznets-ami-docker-patch] vagrant build-sti --binary-only
[Thu Jun  9 08:33:39 EDT 2016] [skuznets-ami-docker-patch] vagrant test-origin --all
Jun 09 09:37:06 hack/test-tools.sh
Jun 09 09:37:06 Running hack/test-tools.sh:19: executing 'tools/junitreport/test/integration.sh' expecting success...
Jun 09 09:37:06 FAILURE after 0.044s: hack/test-tools.sh:19: executing 'tools/junitreport/test/integration.sh' expecting success: the command returned the wrong error code
Jun 09 09:37:06 Standard output from the command:
Jun 09 09:37:06 [INFO] Building junitreport binary for testing...
Jun 09 09:37:06 
Jun 09 09:37:06 Standard error from the command:
Jun 09 09:37:06 junitreport.go:10:2: cannot find package "github.com/openshift/origin/tools/junitreport/pkg/cmd" in any of:
Jun 09 09:37:06 	/usr/lib/golang/src/github.com/openshift/origin/tools/junitreport/pkg/cmd (from $GOROOT)
Jun 09 09:37:06 	($GOPATH not set)
Jun 09 09:37:06 !!! Error in hack/../hack/cmd_util.sh:225
Jun 09 09:37:06 	'return "${return_code}"' exited with status 1
Jun 09 09:37:06 Call stack:
Jun 09 09:37:06 	1: hack/../hack/cmd_util.sh:225 os::cmd::expect_success(...)
Jun 09 09:37:06 	2: hack/test-tools.sh:19 main(...)
Jun 09 09:37:06 Exiting with status 1
Jun 09 09:37:06 make[1]: *** [test-tools] Error 1
Jun 09 09:37:06 make: *** [test] Error 2
```

Do we want to run something that uses the Docker daemon heavily (other than the `vagrant build-origin{-base-images, --images}` that run in the AMI setup?)

**Comment by stevekuznetsov** [comment]
> something that uses the Docker daemon heavily 

i.e. e2e, conformance

**Comment by stevekuznetsov** [comment]
Ran five builds:
##  4/5 flaked on `yum`:
###  2/5 failed in `vagrant build-origin-base-images`
```
```
### 2/5 failed in `vagrant build-origin --images` 
```
Jun 10 08:38:27 --> FROM openshift/origin
Jun 10 08:38:27 --> COPY bin/* /usr/bin/
Jun 10 08:38:27 --> COPY conf/openshift-sdn-ovs.conf /usr/lib/systemd/system/origin-node.service.d/
Jun 10 08:38:27 --> COPY lib/systemd/system/docker.service.d/docker-sdn-ovs.conf /usr/lib/systemd/system/docker.service.d/docker-sdn-ovs.conf
Jun 10 08:38:27 --> COPY scripts/* /usr/local/bin/
Jun 10 08:38:27 --> RUN curl -L -o /etc/yum.repos.d/origin-next-epel-7.repo https://copr.fedoraproject.org/coprs/maxamillion/origin-next/repo/epel-7/maxamillion-origin-next-epel-7.repo &&     INSTALL_PKGS="libmnl libnetfilter_conntrack openvswitch       libnfnetlink iptables iproute bridge-utils procps-ng ethtool socat openssl       binutils xz kmod-libs kmod sysvinit-tools device-mapper-libs dbus       ceph-common iscsi-initiator-utils" &&     yum install -y $INSTALL_PKGS &&     rpm -V $INSTALL_PKGS &&     yum clean all &&     mkdir -p /usr/lib/systemd/system/origin-node.service.d /usr/lib/systemd/system/docker.service.d &&     chmod +x /usr/local/bin/* /usr/bin/openshift-*
Jun 10 08:38:27   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
Jun 10 08:38:27                                  Dload  Upload   Total   Spent    Left  Speed
100   401  100   401    0     0    744      0 --:--:-- --:--:-- --:--:--   743
100   330  100   330    0     0    310      0  0:00:01  0:00:01 --:--:--   310
Jun 10 08:38:27 
Jun 10 08:38:27 
Jun 10 08:38:27  One of the configured repositories failed (Unknown),
Jun 10 08:38:27  and yum doesn't have enough cached data to continue. At this point the only
Jun 10 08:38:27  safe thing yum can do is fail. There are a few ways to work "fix" this:
Jun 10 08:38:27 
Jun 10 08:38:27      1. Contact the upstream for the repository and get them to fix the problem.
Jun 10 08:38:27 
Jun 10 08:38:27      2. Reconfigure the baseurl/etc. for the repository, to point to a working
Jun 10 08:38:27         upstream. This is most often useful if you are using a newer
Jun 10 08:38:27         distribution release than is supported by the repository (and the
Jun 10 08:38:27         packages for the previous distribution release still work).
Jun 10 08:38:27 
Jun 10 08:38:27      3. Disable the repository, so yum won't use it by default. Yum will then
Jun 10 08:38:27         just ignore the repository until you permanently enable it again or use
Jun 10 08:38:27         --enablerepo for temporary usage:
Jun 10 08:38:27 
Jun 10 08:38:27             yum-config-manager --disable <repoid>
Jun 10 08:38:27 
Jun 10 08:38:27      4. Configure the failing repository to be skipped, if it is unavailable.
Jun 10 08:38:27         Note that yum will try to contact the repo. when it runs most commands,
Jun 10 08:38:27         so will have to try and fail each time (and thus. yum will be be much
Jun 10 08:38:27         slower). If it is a very temporary problem though, this is often a nice
Jun 10 08:38:27         compromise:
Jun 10 08:38:27 
Jun 10 08:38:27             yum-config-manager --save --setopt=<repoid>.skip_if_unavailable=true
Jun 10 08:38:27 
Jun 10 08:38:27 Cannot find a valid baseurl for repo: extras/7/x86_64
Jun 10 08:38:27 error: running '/bin/sh -c cd "/var/lib/origin" && curl -L -o /etc/yum.repos.d/origin-next-epel-7.repo https://copr.fedoraproject.org/coprs/maxamillion/origin-next/repo/epel-7/maxamillion-origin-next-epel-7.repo &&     INSTALL_PKGS="libmnl libnetfilter_conntrack openvswitch       libnfnetlink iptables iproute bridge-utils procps-ng ethtool socat openssl       binutils xz kmod-libs kmod sysvinit-tools device-mapper-libs dbus       ceph-common iscsi-initiator-utils" &&     yum install -y $INSTALL_PKGS &&     rpm -V $INSTALL_PKGS &&     yum clean all &&     mkdir -p /usr/lib/systemd/system/origin-node.service.d /usr/lib/systemd/system/docker.service.d &&     chmod +x /usr/local/bin/* /usr/bin/openshift-*' failed with exit code 1
Jun 10 08:38:27 !!! Error in hack/build-images.sh:65
Jun 10 08:38:27 	'"${oc}" ex dockerbuild $2 $1' exited with status 1
Jun 10 08:38:27 Call stack:
Jun 10 08:38:27 	1: hack/build-images.sh:65 build(...)
Jun 10 08:38:27 	2: hack/build-images.sh:99 image(...)
Jun 10 08:38:27 	3: hack/build-images.sh:124 main(...)
Jun 10 08:38:27 Exiting with status 1
Jun 10 08:38:27 make: *** [release] Error 1
```

## 1 flaked in `vagrant test-origin --all`
```
Jun 10 09:45:59 make test-tools test-integration test-assets -o build
Jun 10 09:45:59 hack/test-tools.sh
Jun 10 09:45:59 Running hack/test-tools.sh:19: executing 'tools/junitreport/test/integration.sh' expecting success...
Jun 10 09:45:59 FAILURE after 0.042s: hack/test-tools.sh:19: executing 'tools/junitreport/test/integration.sh' expecting success: the command returned the wrong error code
Jun 10 09:45:59 [INFO] Building junitreport binary for testing...
Jun 10 09:45:59 junitreport.go:10:2: cannot find package "github.com/openshift/origin/tools/junitreport/pkg/cmd" in any of:
Jun 10 09:45:59 	/usr/lib/golang/src/github.com/openshift/origin/tools/junitreport/pkg/cmd (from $GOROOT)
Jun 10 09:45:59 	($GOPATH not set)
Jun 10 09:45:59 !!! Error in hack/../hack/cmd_util.sh:225
Jun 10 09:45:59 	'return "${return_code}"' exited with status 1
Jun 10 09:45:59 Call stack:
Jun 10 09:45:59 	1: hack/../hack/cmd_util.sh:225 os::cmd::expect_success(...)
Jun 10 09:45:59 	2: hack/test-tools.sh:19 main(...)
Jun 10 09:45:59 Exiting with status 1
Jun 10 09:45:59 make[1]: *** [test-tools] Error 1
Jun 10 09:45:59 make: *** [test] Error 2
```

**Comment by stevekuznetsov** [comment]
I'm really at a loss as to how this change could possibly cause `$GOPATH` to become unset in the middle of the test run ... but now we've seen that bizarre error twice.

**Comment by stevekuznetsov** [comment]
@vikram-redhat any clue how these changes could impact a `go build` like seen in the last snippet of log above?

**Comment by stevekuznetsov** [comment]
Sorry, wrong ping -- @rhvgoyal is who I meant

**Comment by stevekuznetsov** [comment]
@danmcp with the new `origin-install` step, we have success.
```
[Tue Jun 14 08:46:08 EDT 2016] [skuznets-ami-dockerd-0] vagrant origin-local-checkout
[Tue Jun 14 08:47:29 EDT 2016] [skuznets-ami-dockerd-0] vagrant origin-init
[Tue Jun 14 08:47:30 EDT 2016] [skuznets-ami-dockerd-0] vagrant up
[Tue Jun 14 08:48:45 EDT 2016] [skuznets-ami-dockerd-0] vagrant build-origin-base
[Tue Jun 14 08:55:04 EDT 2016] [skuznets-ami-dockerd-0] vagrant clone-upstream-repos --clean
[Tue Jun 14 08:55:47 EDT 2016] [skuznets-ami-dockerd-0] vagrant checkout-repos
[Tue Jun 14 08:55:51 EDT 2016] [skuznets-ami-dockerd-0] vagrant build-origin-base-images
[Tue Jun 14 08:59:51 EDT 2016] [skuznets-ami-dockerd-0] vagrant install-origin
[Tue Jun 14 09:07:42 EDT 2016] [skuznets-ami-dockerd-0] vagrant build-origin --images
[Tue Jun 14 09:17:40 EDT 2016] [skuznets-ami-dockerd-0] vagrant build-sti --binary-only
[Tue Jun 14 09:17:47 EDT 2016] [skuznets-ami-dockerd-0] vagrant test-origin --all
[Tue Jun 14 10:15:33 EDT 2016] [skuznets-ami-dockerd-0] finished
```

Of five runs,  three succeed, one fails with the etcd-RAMdisk issue since i haven't got that in my script and one failed with https://github.com/openshift/origin/issues/9309

Do you want further testing?

**Pull request merged**
